### PR TITLE
Application for OpenHD air unit

### PR DESCRIPTION
**Pull request by Consti10**
Hello,

Our community is interested in your cm as a drop-in replacement for the rpi cm4 with various carrier boards.

I myself have a lot of experience with the rockchip platform (RV1126) and would love to contribute by adding sw support for the rpi cam (and more) on radxca cm3.

However, I cannot find any information on the compability of radxca cm3 and MIPI-CSI - does it route out the MIPI-CSI lanes equivalent to the CM4 such that a standart RPI cam can be connected to the RPI CM4 dev board ?
If so, there is a lot of potential for our specific use case.

### CODE REVIEW

**Comment by jack-ma** [comment]
Hi, @Consti10 

Are you using an CM4 with carrier board? If yes, you can just use CM3 with carrier boards such as [Waveshare IO Base]( https://wiki.radxa.com/Rock3/CM3/wavesharecm4iobase), which routes the mipi csi for the RPi camera.

**Comment by Consti10** [comment]
Yes, we are using a CM4 with various CM4 carrier boards. Does this mean you can use the radxca CM3 with the original rpi foundation CM4 carrier board & rpi cam (for example) ? E.g. are the voltages etc. compatible ?

**Comment by jack-ma** [comment]
Yes, you can use the original rpi CM4 carrier boards and the rpi cam. The remaining work is software, ie driver for imx219.

**Comment by Consti10** [comment]
That's great ! I'l happy port the csi drivers & the ohd Projekt to rockchip then. Only thing I need is the radxca cm3, else I have everything at hand.

**Comment by Consti10** [comment]
Are the connectors 2x or 4x lanes ?

**Comment by jack-ma** [comment]
The connector has two 4lanes MiPi CSI.

**Comment by Consti10** [comment]
Hello,
When will you start selling the CM ?

**Comment by hipboi** [comment]
The first public batch should start shipping in 2nd week of Dec.

**Comment by Consti10** [comment]
Is there a way to get earlier access to a board ?

**Comment by hipboi** [comment]
@Consti10  please send me an email with your shipping address: tom@radxa.com , the samples are out soon.

**Pull request closed without merging**
